export const AVATAR_QUEUE = 'AVATAR_QUEUE';
export const RESIZING_AVATAR = 'RESIZING_AVATAR';
export const RESIZING_COVER = 'RESIZING_COVER';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const DEFAULT_AVATAR = 'https://storage.googleapis.com/facebook-storage.appspot.com/user%2Favatar%2Fdefault.jpg';
export const DEFAULT_COVER = 'https://storage.googleapis.com/facebook-storage.appspot.com/user%2Fcover%2Fdefault-cover.png';
export const AVATAR_PATH = 'user/avatar';
export const COVER_PATH = 'user/cover';
export const RESEND_VERIFY_CODE_PERIOD = 120; // 120 s
export const COMMON_USER_PROPERTIES = ['id', 'name', 'avatar'];
